sonar.projectKey=nephropaidi
sonar.projectName=NephroPaidi
sonar.projectVersion=1.0

sonar.sources=BackEnd,FrontEnd/src
sonar.tests=BackEnd,FrontEnd/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/*.min.js,**/*.min.css,**/src/assets/**
sonar.test.inclusions=**/*Test.java,**/*.spec.ts

sonar.java.binaries=BackEnd/**/target/classes
sonar.junit.reportPaths=BackEnd/**/target/surefire-reports

sonar.typescript.tsconfigPath=FrontEnd/tsconfig.json
sonar.sourceEncoding=UTF-8
