-- V29: Expand hospitalization_records to match current embedded clinical sections

ALTER TABLE hospitalization_records
    ADD COLUMN IF NOT EXISTS neonatal_gestational_age_weeks INTEGER,
    ADD COLUMN IF NOT EXISTS neonatal_birth_weight_g INTEGER,
    ADD COLUMN IF NOT EXISTS neonatal_birth_length_cm NUMERIC(5, 2),
    ADD COLUMN IF NOT EXISTS neonatal_birth_head_circumference_cm NUMERIC(5, 2),
    ADD COLUMN IF NOT EXISTS neonatal_hypotrophy VARCHAR(255),
    ADD COLUMN IF NOT EXISTS neonatal_apgar_1min INTEGER,
    ADD COLUMN IF NOT EXISTS neonatal_apgar_5min INTEGER,
    ADD COLUMN IF NOT EXISTS neonatal_apgar_10min INTEGER,
    ADD COLUMN IF NOT EXISTS neonatal_pregnancy_type VARCHAR(255),
    ADD COLUMN IF NOT EXISTS neonatal_delivery_mode VARCHAR(255),
    ADD COLUMN IF NOT EXISTS neonatal_delivery_induced BOOLEAN,
    ADD COLUMN IF NOT EXISTS resp_pathology_type VARCHAR(255),
    ADD COLUMN IF NOT EXISTS resp_surfactant_admin VARCHAR(255),
    ADD COLUMN IF NOT EXISTS resp_bpd_severity VARCHAR(255),
    ADD COLUMN IF NOT EXISTS resp_ventilatory_support_28d BOOLEAN,
    ADD COLUMN IF NOT EXISTS resp_ventilatory_support_36wks BOOLEAN,
    ADD COLUMN IF NOT EXISTS card_pathology_type VARCHAR(255),
    ADD COLUMN IF NOT EXISTS card_pda_treatment VARCHAR(255),
    ADD COLUMN IF NOT EXISTS neuro_ivh_grade VARCHAR(255),
    ADD COLUMN IF NOT EXISTS neuro_periventricular_leukomalacia BOOLEAN,
    ADD COLUMN IF NOT EXISTS neuro_seizures BOOLEAN,
    ADD COLUMN IF NOT EXISTS neuro_coding_score VARCHAR(255),
    ADD COLUMN IF NOT EXISTS infect_maternal_fetal_infection VARCHAR(255),
    ADD COLUMN IF NOT EXISTS infect_multi_resistant_bacteria BOOLEAN,
    ADD COLUMN IF NOT EXISTS infect_late_infection BOOLEAN,
    ADD COLUMN IF NOT EXISTS audit_screening_status BOOLEAN,
    ADD COLUMN IF NOT EXISTS audit_hearing_result VARCHAR(255),
    ADD COLUMN IF NOT EXISTS audit_hearing_coding_score VARCHAR(255),
    ADD COLUMN IF NOT EXISTS vision_rop_stage VARCHAR(255),
    ADD COLUMN IF NOT EXISTS vision_rop_treatment VARCHAR(255),
    ADD COLUMN IF NOT EXISTS vision_coding_score VARCHAR(255),
    ADD COLUMN IF NOT EXISTS hosp_nephro_egfr NUMERIC(8, 2),
    ADD COLUMN IF NOT EXISTS hosp_nephro_k NUMERIC(4, 2),
    ADD COLUMN IF NOT EXISTS serum_creatinine_umol_l NUMERIC(8, 2),
    ADD COLUMN IF NOT EXISTS serum_creatinine_mg_dl NUMERIC(8, 2),
    ADD COLUMN IF NOT EXISTS cystatin_c_mg_l NUMERIC(8, 2),
    ADD COLUMN IF NOT EXISTS hosp_nephro_ckd_stage VARCHAR(255),
    ADD COLUMN IF NOT EXISTS ckd_cause VARCHAR(255),
    ADD COLUMN IF NOT EXISTS urine_protein_creatinine_ratio NUMERIC(8, 2),
    ADD COLUMN IF NOT EXISTS proteinuria_category VARCHAR(255),
    ADD COLUMN IF NOT EXISTS hematuria_level VARCHAR(255),
    ADD COLUMN IF NOT EXISTS dysmorphic_erythrocytes BOOLEAN,
    ADD COLUMN IF NOT EXISTS leukocyturia BOOLEAN,
    ADD COLUMN IF NOT EXISTS serum_albumin_g_l NUMERIC(8, 2),
    ADD COLUMN IF NOT EXISTS serum_sodium_mmol_l NUMERIC(8, 2),
    ADD COLUMN IF NOT EXISTS serum_potassium_mmol_l NUMERIC(8, 2),
    ADD COLUMN IF NOT EXISTS serum_bicarbonate_mmol_l NUMERIC(8, 2),
    ADD COLUMN IF NOT EXISTS serum_phosphate_mmol_l NUMERIC(8, 2),
    ADD COLUMN IF NOT EXISTS serum_calcium_mmol_l NUMERIC(8, 2),
    ADD COLUMN IF NOT EXISTS pth_pg_ml NUMERIC(8, 2),
    ADD COLUMN IF NOT EXISTS vitamin_d_25oh_nmol_l NUMERIC(8, 2),
    ADD COLUMN IF NOT EXISTS serum_urea_mmol_l NUMERIC(8, 2),
    ADD COLUMN IF NOT EXISTS hus_present BOOLEAN,
    ADD COLUMN IF NOT EXISTS hus_type VARCHAR(255),
    ADD COLUMN IF NOT EXISTS aki_present BOOLEAN,
    ADD COLUMN IF NOT EXISTS aki_origin VARCHAR(255),
    ADD COLUMN IF NOT EXISTS nephrotic_syndrome BOOLEAN,
    ADD COLUMN IF NOT EXISTS hereditary_nephropathy BOOLEAN;
