spring:
  application:
    name: ml-prediction-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}

management:
  endpoints:
    web:
      exposure:
        include: health,info
