apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-service
  namespace: nephro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication-service
  template:
    metadata:
      labels:
        app: communication-service
    spec:
      containers:
        - name: communication-service
          image: nephropaidi-communication-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka:8761/eureka"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "communication-service"
            - name: KEYCLOAK_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: nephro-common-config
                  key: KEYCLOAK_ISSUER_URI
            - name: KEYCLOAK_JWK_SET_URI
              valueFrom:
                configMapKeyRef:
                  name: nephro-common-config
                  key: KEYCLOAK_JWK_SET_URI
            - name: USER_SERVICE_BASE_URL
              value: "http://user-service:8090"
            - name: ADMINISTRATION_SERVICE_BASE_URL
              value: "http://administration-service:8087"
            - name: INTERNAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nephro-app-secrets
                  key: INTERNAL_API_KEY
            - name: ENVIRONMENT
              value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: communication-service
  namespace: nephro
spec:
  selector:
    app: communication-service
  ports:
    - name: http
      port: 8085
      targetPort: 8085

