apiVersion: apps/v1
kind: Deployment
metadata:
  name: egfr-ml-service
  namespace: nephro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egfr-ml-service
  template:
    metadata:
      labels:
        app: egfr-ml-service
    spec:
      containers:
        - name: egfr-ml-service
          image: nephropaidi-egfr-ml-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8092
---
apiVersion: v1
kind: Service
metadata:
  name: egfr-ml-service
  namespace: nephro
spec:
  selector:
    app: egfr-ml-service
  ports:
    - name: http
      port: 8092
      targetPort: 8092

