apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - keycloak.yaml
  - rabbitmq.yaml
  - eureka.yaml
  - config-server.yaml
  - user-service.yaml
  - administration-service.yaml
  - communication-service.yaml
  - procedure-service.yaml
  - ops-service.yaml
  - pharmacy-service.yaml
  - api-gateway.yaml
