apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - keycloak.yaml
  - rabbitmq.yaml
  - eureka.yaml
  - config-server.yaml
  - user-service.yaml
  - administration-service.yaml
  - communication-service.yaml
  - clinical-service.yaml
  - ai-clinical-service.yaml
  - egfr-ml-service.yaml
  - ai-pharmacy-service.yaml
  - core-ops-service.yaml
  - procedure-service.yaml
  - ops-service.yaml
  - pharmacy-service.yaml
  - api-gateway.yaml
  - prometheus-config.yaml
  - prometheus.yaml
  - grafana-datasource.yaml
  - grafana-dashboard-provider.yaml
  - grafana-dashboard.yaml
  - grafana.yaml
