apiVersion: v1
kind: Secret
metadata:
  name: nephro-app-secrets
  namespace: nephro
type: Opaque
stringData:
  INTERNAL_API_KEY: "my-super-secret-internal-key"
  KEYCLOAK_ADMIN_PASSWORD: "admin123"
  KEYCLOAK_AUTH_CLIENT_SECRET: "nephro-backend-secret"
  USER_DB_PASSWORD: "npg_Zb1Kda5LPlin"
  CLINICAL_DB_PASSWORD: "npg_Zb1Kda5LPlin"
  OPS_DB_PASSWORD: "npg_Zb1Kda5LPlin"
  PHARMACY_DB_PASSWORD: "npg_Zb1Kda5LPlin"
