apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-service
  namespace: nephro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ops-service
  template:
    metadata:
      labels:
        app: ops-service
    spec:
      containers:
        - name: ops-service
          image: nephropaidi-ops-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:8888"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://ep-cool-breeze-agqhhjlc.c-2.eu-central-1.aws.neon.tech/nephros_ops_service_db?sslmode=require&channel_binding=require"
            - name: SPRING_DATASOURCE_USERNAME
              value: "neondb_owner"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "npg_Zb1Kda5LPlin"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.postgresql.Driver"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://localhost:8080/realms/nephrospaidi"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: "http://keycloak:8080/realms/nephrospaidi/protocol/openid-connect/certs"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka:8761/eureka"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "ops-service"
            - name: KEYCLOAK_ISSUER_URI
              value: "http://localhost:8080/realms/nephrospaidi"
            - name: KEYCLOAK_JWK_SET_URI
              value: "http://keycloak:8080/realms/nephrospaidi/protocol/openid-connect/certs"
            - name: ENVIRONMENT
              value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: ops-service
  namespace: nephro
spec:
  selector:
    app: ops-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
